name: Attendance Bot

permissions:
  contents: read

on:
  schedule:
    - cron: "45 3 * * *"     # IN at 09:15 AM IST
    - cron: "30 12 * * *"    # OUT at 06:00 PM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug Time
        run: |
          echo "Triggered at UTC time: $(date -u)"
          echo "Triggered at IST time: $(TZ='Asia/Kolkata' date)"
          echo "Event schedule: ${{ github.event.schedule }}"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        working-directory: NewProject
        run: chmod +x gradlew

      - name: Run Attendance Bot (Mode IN or OUT)
        working-directory: NewProject
        env:
          ATT_MODE: ${{ github.event.schedule == '45 3 * * *' && 'IN' || 'OUT' }}
          HRONE_USERNAME: ${{ secrets.HRONE_USERNAME }}
          HRONE_PASSWORD: ${{ secrets.HRONE_PASSWORD }}
          HRONE_COOKIE: ${{ secrets.HRONE_COOKIE }}
        run: ./gradlew bootRun
