name: Attendance Bot

on:
  schedule:
    - cron: "45 3 * * *"   # 09:15 IST
    - cron: "30 12 * * *"  # 06:00 PM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        working-directory: NewProject
        run: chmod +x gradlew

      - name: Run Attendance Bot
        working-directory: NewProject
        env:
          HRONE_USERNAME: ${{ secrets.HRONE_USERNAME }}
          HRONE_PASSWORD: ${{ secrets.HRONE_PASSWORD }}
          HRONE_COOKIE: ${{ secrets.HRONE_COOKIE }}
        run: ./gradlew bootRun
